M48
; DRILL file {KiCad (6.0.4)} date Tue Oct 25 01:53:49 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-25T01:53:49-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X0.7421Y0.0591
X0.7421Y0.0591
X0.7421Y-0.0591
X0.7421Y-0.0591
T0
M30
